services:
  esp8266-build:
    hostname: esp8266-build
    platform: linux/amd64
    build:
      context: ./docker
      dockerfile: Dockerfile.esp8266-rtos
    working_dir: /work/firmware
    environment:
      - IDF_PATH=/opt/esp/ESP8266_RTOS_SDK
    volumes:
      - ./firmware:/work/firmware
      - idf_cache:/root/.espressif
    command: bash
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
volumes:
  idf_cache:
